name = "neodynix-pages"
compatibility_date = "2025-11-07"

# Required for Pages Functions
pages_build_output_dir = "."

node_compat = true

[[pages.functions]]
  directory = "functions"
  external = [
    "@cloudflare/ai",
    "@supabase/supabase-js"
  ]

[ai]
binding = "AI"
